# -*- coding: utf-8 -*-
"""Codigoparaappstreamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7a_S-yVrT46TXoh2_0gh48RSUufAhRV
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Codigoparaappstreamlit.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# from sklearn.linear_model import LinearRegression
# 
# st.write(''' # Predicción de Temperatura en Ciudades de México ''')
# st.image("city.png", caption="Predicción de temperatura por ciudad, mes y año.")
# 
# st.header('Datos de evaluación')
# 
# def user_input_features():
#   Mes = st.number_input('Mes:', min_value=1, max_value=12, value=1, step=1)
#   Año = st.number_input('Año:', min_value=1900, max_value=2100, value=2024, step=1)
#   Ciudad = st.text_input('Ciudad:')
# 
#   user_input_data = {
#                      'Month': Mes,
#                      'Year': Año,
#                      'City': Ciudad
#                      }
# 
#   features = pd.DataFrame(user_input_data, index=[0])
# 
#   return features
# 
# df = user_input_features()
# 
# temperaturas = pd.read_csv('AmericaTemperaturesByCityCorrecto.csv', encoding='latin-1')
# 
# temperaturas['City_encoded'] = temperaturas['City'].astype('category').cat.codes
# 
# X = temperaturas[['Month', 'Year', 'City_encoded']]
# Y = temperaturas['Temperature']
# 
# model = LinearRegression()
# model.fit(X, Y)
# 
# df['City_encoded'] = df['City'].astype('category').map(
#     dict(zip(temperaturas['City'].astype('category').cat.categories,
#              temperaturas['City'].astype('category').cat.codes))
# )
# 
# if df['City_encoded'].isna().any():
#     st.subheader('Predicción')
#     st.write('Ciudad no encontrada en los datos.')
# else:
#     prediction = model.predict(df[['Month', 'Year', 'City_encoded']])
# 
#     st.subheader('Predicción')
#     st.write('Temperatura esperada:', round(float(prediction), 2), '°C')